site_name: translotator
site_url: ""
theme:
  name: material
  # logo: path_to_logo.png
  features:
    - navigation.tabs
    # - navigation.instant

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax_config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/always-no-cache.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Main: 
      - "README.md"
      - "Matrix based Object": "matrix_based_objects.md"
      - "Matrix & Vector" : "matrix_vector.md"
      - "Number Systems" : 
          - "Complex Number" : "complex_number.md"
          - "Quaternion" : "quaternion.md"
          - "Dual Number" : "dual_number.md"
          - "Dual Quaternion" : "dual_quaternion.md"
      - "Rotation Groups" : 
          - "Unit Complex Number" : "unit_complex_number.md"
          - "Unit Quaternion" : "unit_quaternion.md"
          - "SO Group" : "so_group.md"
      - "Rotation Representation Tools" : 
          - "Euler Angle" : "euler_angle.md"
          - "Axis Angle" : "axis_angle.md"
      - "Homogeneous Transformation" : 
          - "SE Group" : se_group.md
  - Specifications(MkDoxy):
      - "Links": "translotator/links.md"
      - "Classes":
          - "Class List": "translotator/annotated.md"
          - "Class Index": "translotator/classes.md"
          - "Class Hierarchy": "translotator/hierarchy.md"
          - "Class Members": "translotator/class_members.md"
          - "Class Member Functions": "translotator/class_member_functions.md"
          - "Class Member Variables": "translotator/class_member_variables.md"
          - "Class Member Typedefs": "translotator/class_member_typedefs.md"
          - "Class Member Enumerations": "translotator/class_member_enums.md"
      - "Namespaces":
          - "Namespace List": "translotator/namespaces.md"
          - "Namespace Members": "translotator/namespace_members.md"
          - "Namespace Member Functions": "translotator/namespace_member_functions.md"
          - "Namespace Member Variables": "translotator/namespace_member_variables.md"
          - "Namespace Member Typedefs": "translotator/namespace_member_typedefs.md"
          - "Namespace Member Enumerations": "translotator/namespace_member_enums.md"
      - "Functions": "translotator/functions.md"
      - "Variables": "translotator/variables.md"
      - "Macros": "translotator/macros.md"
      - "Files": "translotator/files.md"

plugins:
  - search
  - mkdoxy:
      projects:
        translotator:
          src-dirs: include/translotator
          full-doc: True
          doxy-cfg: # standard doxygen configuration (key: value)
            RECURSIVE: True # recursive search in source directories