#pragma once

namespace CMAKE_CPP_TEMPLATE
{
#define CMAKE_CPP_TEMPLATE_VERSION "0.0.0"

#define CMAKE_CPP_TEMPLATE_MAJOR_VERSION 0
#define CMAKE_CPP_TEMPLATE_MINOR_VERSION 0
#define CMAKE_CPP_TEMPLATE_PATCH_VERSION 0
#define CMAKE_CPP_TEMPLATE_TWEAK_VERSION "a708453"
}
