#pragma once

namespace TRANSLOTATOR
{
#define TRANSLOTATOR_VERSION "0.0.0"

#define TRANSLOTATOR_MAJOR_VERSION 0
#define TRANSLOTATOR_MINOR_VERSION 0
#define TRANSLOTATOR_PATCH_VERSION 0
#define TRANSLOTATOR_TWEAK_VERSION "eb06f40"
}
