#pragma once

#include "../config.hpp"

namespace translotator
{

#ifdef CONFIG_TRANSLOTATOR_DEFAULT_FLOATING_POINT_PRECISION_32
#define TRANSLOTATOR_DEFAULT_FLOATING_POINT_TYPE float
#elif CONFIG_TRANSLOTATOR_DEFAULT_FLOATING_POINT_PRECISION_64
#define TRANSLOTATOR_DEFAULT_FLOATING_POINT_TYPE double
#elif CONFIG_TRANSLOTATOR_DEFAULT_FLOATING_POINT_PRECISION_128
#define TRANSLOTATOR_DEFAULT_FLOATING_POINT_TYPE long double
#endif

}